# Generated by Django 4.1.5 on 2023-01-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceinventories',
            name='maintenanceDate',
            field=models.CharField(max_length=100),
        ),
    ]
