# Generated by Django 4.1.5 on 2023-01-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_alter_maintenanceinventories_maintenancedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceinventories',
            name='maintenanceDate',
            field=models.DateField(),
        ),
    ]
